# Application Configuration File 3

# Database Configuration
database:
  host: db-3.example.com
  port: 5432
  name: app_db_3
  username: app_user_3
  password: ${DB_PASSWORD}
  ssl_mode: require
  max_connections: 100
  connection_timeout: 30
  pool_size: 20

# Redis Configuration
redis:
  host: redis-3.example.com
  port: 6379
  password: ${REDIS_PASSWORD}
  database: 0
  max_connections: 50
  connection_timeout: 10

# Application Settings
app:
  name: "Test Application 3"
  version: "1.3.0"
  environment: production
  debug: false
  log_level: info
  port: 8083
  host: 0.0.0.0

# Security Configuration
security:
  jwt_secret: ${JWT_SECRET}
  jwt_expiration: 3600
  refresh_token_expiration: 604800
  bcrypt_rounds: 12
  cors_origins:
    - https://app3.example.com
    - https://admin3.example.com
  rate_limit:
    window_ms: 900000
    max_requests: 1000

# Email Configuration
email:
  provider: sendgrid
  api_key: ${SENDGRID_API_KEY}
  from_address: noreply@example3.com
  templates:
    welcome: welcome_template_3
    password_reset: password_reset_template_3
    verification: verification_template_3

# File Storage
storage:
  provider: aws_s3
  bucket: app-files-3
  region: us-east-1
  access_key: ${AWS_ACCESS_KEY}
  secret_key: ${AWS_SECRET_KEY}
  max_file_size: 10485760
  allowed_types:
    - image/jpeg
    - image/png
    - application/pdf
    - text/plain

# Monitoring
monitoring:
  provider: datadog
  api_key: ${DATADOG_API_KEY}
  app_key: ${DATADOG_APP_KEY}
  metrics:
    enabled: true
    interval: 60
  logging:
    level: info
    format: json
    output: stdout

# Feature Flags
features:
  new_ui: true
  advanced_analytics: false
  beta_features: true
  maintenance_mode: false
  user_registration: true
  social_login: true

# API Configuration
api:
  version: v3
  base_url: https://api3.example.com
  rate_limit: 1000
  timeout: 30
  pagination:
    default_limit: 20
    max_limit: 100
  documentation:
    enabled: true
    path: /docs
    title: "API Documentation 3"
